import type { Aluno, Curso, Inscricao, Instrutor, Sindicato, Turma } from "./types";

export const sindicato: Sindicato = {
  id: "sindicato-sjc",
  nome: "Sindicato Rural de São José dos Campos",
  municipio: "São José dos Campos",
  cnpj: "00.000.000/0001-00",
  slug: "sao-jose-dos-campos",
  plano: "pro",
  assinaturaAtiva: true,
  createdAt: "2026-08-03T09:00:00.000-03:00",
  marca: {
    logoUrl: "/sindicato-sjc.svg",
    senarLogoUrl: "/senar-sp.svg",
    corPrimaria: "#087a3d",
    corSecundaria: "#0b6f67",
  },
};

export const cursos: Curso[] = [
  {
    id: "curso-goiaba-integrada",
    sindicatoId: sindicato.id,
    nome: "Produção Integrada de Goiaba",
    tipo: "FPR",
    eixo: "Fruticultura",
    cargaHoraria: 24,
    descricao:
      "Capacitação para manejo integrado, qualidade de fruto, rastreabilidade e boas práticas na produção de goiaba.",
    objetivos: [
      "Organizar o manejo por talhão",
      "Reduzir perdas no período de colheita",
      "Preparar documentação para comercialização",
    ],
    imagemUrl: null,
    codigoSenar: "SENAR-SP-FRU-024",
    ativo: true,
  },
  {
    id: "curso-nr-31-maquinas",
    sindicatoId: sindicato.id,
    nome: "NR 31.12 - Segurança em Máquinas Agrícolas",
    tipo: "FPR",
    eixo: "Segurança do Trabalho",
    cargaHoraria: 16,
    descricao:
      "Treinamento obrigatório para operação segura de máquinas, implementos e equipamentos no meio rural.",
    objetivos: [
      "Aplicar rotinas de segurança",
      "Reconhecer riscos operacionais",
      "Registrar conformidades para fiscalização",
    ],
    imagemUrl: null,
    codigoSenar: "SENAR-SP-NR31-016",
    ativo: true,
  },
  {
    id: "curso-bovinocultura-corte",
    sindicatoId: sindicato.id,
    nome: "Bovinocultura de Corte: Manejo e Nutrição",
    tipo: "FPR",
    eixo: "Pecuária",
    cargaHoraria: 20,
    descricao:
      "Formação prática para melhorar ganho de peso, manejo de pastagens e eficiência alimentar do rebanho.",
    objetivos: [
      "Montar calendário sanitário",
      "Ajustar lotação de pasto",
      "Acompanhar indicadores de ganho",
    ],
    imagemUrl: null,
    codigoSenar: "SENAR-SP-PEC-020",
    ativo: true,
  },
  {
    id: "curso-boas-praticas",
    sindicatoId: sindicato.id,
    nome: "Boas Práticas de Aplicação de Defensivos",
    tipo: "FPR",
    eixo: "Agricultura",
    cargaHoraria: 16,
    descricao:
      "Uso responsável de defensivos, escolha de EPI, regulagem de equipamentos e segurança durante a aplicação.",
    objetivos: [
      "Selecionar EPI adequado",
      "Regular equipamentos de aplicação",
      "Registrar operações com segurança",
    ],
    imagemUrl: null,
    codigoSenar: "SENAR-SP-AGR-016",
    ativo: true,
  },
  {
    id: "curso-drone-pulverizacao",
    sindicatoId: sindicato.id,
    nome: "Operação de Drones na Pulverização Agrícola",
    tipo: "Tecnico",
    eixo: "Mecanização Agrícola",
    cargaHoraria: 24,
    descricao:
      "Uso de aeronaves remotamente pilotadas (RPA) para pulverização localizada, com regulagem, segurança e registro de aplicações.",
    objetivos: [
      "Planejar voos e faixas de aplicação",
      "Calibrar taxa e deriva",
      "Cumprir exigências de segurança e ambientais",
    ],
    imagemUrl: null,
    codigoSenar: "SENAR-SP-MEC-024",
    ativo: true,
  },
  {
    id: "curso-ordenha-leite",
    sindicatoId: sindicato.id,
    nome: "Ordenha Higiênica e Qualidade do Leite",
    tipo: "FPR",
    eixo: "Pecuária de Leite",
    cargaHoraria: 16,
    descricao:
      "Boas práticas de ordenha, higiene do úbere e resfriamento para elevar a qualidade do leite e reduzir a contagem de células somáticas.",
    objetivos: [
      "Padronizar a rotina de ordenha",
      "Controlar mastite e CCS",
      "Garantir a cadeia de frio do leite",
    ],
    imagemUrl: null,
    codigoSenar: "SENAR-SP-LEI-016",
    ativo: true,
  },
  {
    id: "curso-apicultura",
    sindicatoId: sindicato.id,
    nome: "Apicultura: Produção Sustentável de Mel",
    tipo: "FPR",
    eixo: "Apicultura",
    cargaHoraria: 20,
    descricao:
      "Manejo de colmeias, florada do Vale do Paraíba, colheita e beneficiamento do mel com foco em renda complementar para a família rural.",
    objetivos: [
      "Instalar e manejar apiários",
      "Realizar colheita higiênica",
      "Beneficiar e rotular o mel",
    ],
    imagemUrl: null,
    codigoSenar: "SENAR-SP-API-020",
    ativo: true,
  },
  {
    id: "curso-olericultura",
    sindicatoId: sindicato.id,
    nome: "Olericultura: Produção de Hortaliças",
    tipo: "FPR",
    eixo: "Olericultura",
    cargaHoraria: 24,
    descricao:
      "Produção de hortaliças folhosas e de fruto com manejo de solo, irrigação e comercialização em feiras e programas institucionais.",
    objetivos: [
      "Planejar canteiros e sucessão de cultivo",
      "Manejar irrigação e adubação",
      "Acessar mercados locais (PNAE/PAA)",
    ],
    imagemUrl: null,
    codigoSenar: "SENAR-SP-OLE-024",
    ativo: true,
  },
  {
    id: "curso-gestao-propriedade",
    sindicatoId: sindicato.id,
    nome: "Gestão da Propriedade Rural",
    tipo: "PromocaoSocial",
    eixo: "Gestão e Empreendedorismo",
    cargaHoraria: 16,
    descricao:
      "Controle de custos, fluxo de caixa e planejamento da propriedade para tomada de decisão, inspirado no Programa Empresário Rural do SENAR-SP.",
    objetivos: [
      "Organizar registros e custos",
      "Montar fluxo de caixa",
      "Planejar investimentos da safra",
    ],
    imagemUrl: null,
    codigoSenar: "SENAR-SP-GES-016",
    ativo: true,
  },
];

export const instrutores: Instrutor[] = [
  {
    id: "instrutor-ana-paula",
    sindicatoId: sindicato.id,
    nome: "Ana Paula Ribeiro",
    cpf: "000.000.000-00",
    telefone: "+5512999990001",
    email: "ana.instrutora@example.com",
    especialidades: ["Fruticultura", "Boas práticas"],
    credenciado: true,
  },
  {
    id: "instrutor-carlos",
    sindicatoId: sindicato.id,
    nome: "Carlos Henrique Mota",
    cpf: "000.000.000-01",
    telefone: "+5512999990002",
    email: "carlos.instrutor@example.com",
    especialidades: ["Segurança do Trabalho", "Máquinas agrícolas"],
    credenciado: true,
  },
];

export const turmas: Turma[] = [
  {
    id: "turma-goiaba-agosto",
    sindicatoId: sindicato.id,
    cursoId: "curso-goiaba-integrada",
    cursoNome: "Produção Integrada de Goiaba",
    instrutorId: "instrutor-ana-paula",
    instrutorNome: "Ana Paula Ribeiro",
    local: "Sede do Sindicato Rural",
    municipio: "São José dos Campos",
    encontros: [
      { data: "2026-08-18T08:00:00.000-03:00", cargaHoraria: 8 },
      { data: "2026-08-19T08:00:00.000-03:00", cargaHoraria: 8 },
      { data: "2026-08-20T08:00:00.000-03:00", cargaHoraria: 8 },
    ],
    capacidade: 24,
    vagasPreenchidas: 18,
    status: "confirmada",
    publicadaNoPortal: true,
    confirmacaoAutomatica: false,
    whatsappGrupoUrl: "https://wa.me/5512999999999",
    supervisorSenar: { nome: "Renata Lima", contato: "renata.senar@example.com" },
    numeroOficio: "OF-2026-0818",
    createdAt: "2026-08-01T10:00:00.000-03:00",
    updatedAt: "2026-08-03T11:00:00.000-03:00",
  },
  {
    id: "turma-nr31-agosto",
    sindicatoId: sindicato.id,
    cursoId: "curso-nr-31-maquinas",
    cursoNome: "NR 31.12 - Segurança em Máquinas Agrícolas",
    instrutorId: "instrutor-carlos",
    instrutorNome: "Carlos Henrique Mota",
    local: "Fazenda Escola Parceira",
    municipio: "São José dos Campos",
    encontros: [
      { data: "2026-08-24T08:00:00.000-03:00", cargaHoraria: 8 },
      { data: "2026-08-25T08:00:00.000-03:00", cargaHoraria: 8 },
    ],
    capacidade: 20,
    vagasPreenchidas: 20,
    status: "mobilizacao",
    publicadaNoPortal: true,
    confirmacaoAutomatica: false,
    whatsappGrupoUrl: "https://wa.me/5512888888888",
    supervisorSenar: { nome: "Renata Lima", contato: "renata.senar@example.com" },
    numeroOficio: null,
    createdAt: "2026-08-02T14:00:00.000-03:00",
    updatedAt: "2026-08-03T11:00:00.000-03:00",
  },
  {
    id: "turma-bovinos-setembro",
    sindicatoId: sindicato.id,
    cursoId: "curso-bovinocultura-corte",
    cursoNome: "Bovinocultura de Corte: Manejo e Nutrição",
    instrutorId: null,
    instrutorNome: null,
    local: "Bairro Rural do Jaguari",
    municipio: "São José dos Campos",
    encontros: [
      { data: "2026-09-09T08:00:00.000-03:00", cargaHoraria: 10 },
      { data: "2026-09-10T08:00:00.000-03:00", cargaHoraria: 10 },
    ],
    capacidade: 25,
    vagasPreenchidas: 7,
    status: "solicitada",
    publicadaNoPortal: true,
    confirmacaoAutomatica: true,
    whatsappGrupoUrl: "https://wa.me/5512777777777",
    supervisorSenar: null,
    numeroOficio: "OF-2026-0909",
    createdAt: "2026-08-03T09:30:00.000-03:00",
    updatedAt: "2026-08-03T11:00:00.000-03:00",
  },
  {
    id: "turma-drone-setembro",
    sindicatoId: sindicato.id,
    cursoId: "curso-drone-pulverizacao",
    cursoNome: "Operação de Drones na Pulverização Agrícola",
    instrutorId: "instrutor-carlos",
    instrutorNome: "Carlos Henrique Mota",
    local: "Fazenda Escola Parceira",
    municipio: "São José dos Campos",
    encontros: [
      { data: "2026-09-15T08:00:00.000-03:00", cargaHoraria: 8 },
      { data: "2026-09-16T08:00:00.000-03:00", cargaHoraria: 8 },
      { data: "2026-09-17T08:00:00.000-03:00", cargaHoraria: 8 },
    ],
    capacidade: 15,
    vagasPreenchidas: 9,
    status: "confirmada",
    publicadaNoPortal: true,
    confirmacaoAutomatica: false,
    whatsappGrupoUrl: "https://wa.me/5512999999901",
    supervisorSenar: { nome: "Renata Lima", contato: "renata.senar@example.com" },
    numeroOficio: "OF-2026-0915",
    createdAt: "2026-08-01T10:00:00.000-03:00",
    updatedAt: "2026-08-03T11:00:00.000-03:00",
  },
  {
    id: "turma-ordenha-agosto",
    sindicatoId: sindicato.id,
    cursoId: "curso-ordenha-leite",
    cursoNome: "Ordenha Higiênica e Qualidade do Leite",
    instrutorId: null,
    instrutorNome: null,
    local: "Bairro Rural de São Francisco Xavier",
    municipio: "São José dos Campos",
    encontros: [
      { data: "2026-08-28T08:00:00.000-03:00", cargaHoraria: 8 },
      { data: "2026-08-29T08:00:00.000-03:00", cargaHoraria: 8 },
    ],
    capacidade: 20,
    vagasPreenchidas: 6,
    status: "mobilizacao",
    publicadaNoPortal: true,
    confirmacaoAutomatica: true,
    whatsappGrupoUrl: null,
    supervisorSenar: null,
    numeroOficio: null,
    createdAt: "2026-08-02T09:00:00.000-03:00",
    updatedAt: "2026-08-03T11:00:00.000-03:00",
  },
  {
    id: "turma-apicultura-setembro",
    sindicatoId: sindicato.id,
    cursoId: "curso-apicultura",
    cursoNome: "Apicultura: Produção Sustentável de Mel",
    instrutorId: "instrutor-ana-paula",
    instrutorNome: "Ana Paula Ribeiro",
    local: "Sede do Sindicato Rural",
    municipio: "São José dos Campos",
    encontros: [
      { data: "2026-09-22T08:00:00.000-03:00", cargaHoraria: 10 },
      { data: "2026-09-23T08:00:00.000-03:00", cargaHoraria: 10 },
    ],
    capacidade: 18,
    vagasPreenchidas: 12,
    status: "solicitada",
    publicadaNoPortal: true,
    confirmacaoAutomatica: false,
    whatsappGrupoUrl: "https://wa.me/5512999999902",
    supervisorSenar: { nome: "Renata Lima", contato: "renata.senar@example.com" },
    numeroOficio: "OF-2026-0922",
    createdAt: "2026-08-02T15:00:00.000-03:00",
    updatedAt: "2026-08-03T11:00:00.000-03:00",
  },
  {
    id: "turma-gestao-agosto",
    sindicatoId: sindicato.id,
    cursoId: "curso-gestao-propriedade",
    cursoNome: "Gestão da Propriedade Rural",
    instrutorId: "instrutor-ana-paula",
    instrutorNome: "Ana Paula Ribeiro",
    local: "Sede do Sindicato Rural",
    municipio: "São José dos Campos",
    encontros: [
      { data: "2026-08-26T18:30:00.000-03:00", cargaHoraria: 4 },
      { data: "2026-08-27T18:30:00.000-03:00", cargaHoraria: 4 },
      { data: "2026-08-28T18:30:00.000-03:00", cargaHoraria: 4 },
      { data: "2026-08-29T18:30:00.000-03:00", cargaHoraria: 4 },
    ],
    capacidade: 30,
    vagasPreenchidas: 22,
    status: "confirmada",
    publicadaNoPortal: true,
    confirmacaoAutomatica: false,
    whatsappGrupoUrl: "https://wa.me/5512999999903",
    supervisorSenar: { nome: "Renata Lima", contato: "renata.senar@example.com" },
    numeroOficio: "OF-2026-0826",
    createdAt: "2026-08-01T14:00:00.000-03:00",
    updatedAt: "2026-08-03T11:00:00.000-03:00",
  },
  {
    id: "turma-olericultura-outubro",
    sindicatoId: sindicato.id,
    cursoId: "curso-olericultura",
    cursoNome: "Olericultura: Produção de Hortaliças",
    instrutorId: null,
    instrutorNome: null,
    local: "Bairro Rural do Banhado",
    municipio: "São José dos Campos",
    encontros: [
      { data: "2026-10-06T08:00:00.000-03:00", cargaHoraria: 8 },
      { data: "2026-10-07T08:00:00.000-03:00", cargaHoraria: 8 },
      { data: "2026-10-08T08:00:00.000-03:00", cargaHoraria: 8 },
    ],
    capacidade: 22,
    vagasPreenchidas: 4,
    status: "mobilizacao",
    publicadaNoPortal: true,
    confirmacaoAutomatica: true,
    whatsappGrupoUrl: null,
    supervisorSenar: null,
    numeroOficio: null,
    createdAt: "2026-08-03T08:00:00.000-03:00",
    updatedAt: "2026-08-03T11:00:00.000-03:00",
  },
];

export const alunos: Aluno[] = [
  {
    id: "aluno-marina",
    sindicatoId: sindicato.id,
    nome: "Marina Costa",
    cpf: "123.456.789-10",
    dataNascimento: "1989-04-11",
    telefone: "+5512988880001",
    email: "marina.costa@example.com",
    categoria: "produtor",
    propriedade: {
      nome: "Sitio Santa Rita",
      municipio: "São José dos Campos",
      car: "SP-3549904-00001",
      itr: "ITR-2026-001",
      atividadePrincipal: "Fruticultura",
    },
    comprovanteAtividadeUrl: "/comprovantes/marina.pdf",
    associado: true,
    cursosConcluidos: ["curso-boas-praticas"],
    createdAt: "2026-07-12T08:00:00.000-03:00",
    updatedAt: "2026-08-03T10:00:00.000-03:00",
  },
  {
    id: "aluno-joao",
    sindicatoId: sindicato.id,
    nome: "Joao Marcos Silva",
    cpf: "123.456.789-11",
    dataNascimento: "1981-10-02",
    telefone: "+5512988880002",
    email: "joao.silva@example.com",
    categoria: "familiar",
    propriedade: {
      nome: "Fazenda Boa Vista",
      municipio: "São José dos Campos",
      car: "SP-3549904-00002",
      itr: null,
      atividadePrincipal: "Pecuária de corte",
    },
    comprovanteAtividadeUrl: "/comprovantes/joao.pdf",
    associado: false,
    cursosConcluidos: [],
    createdAt: "2026-07-18T08:00:00.000-03:00",
    updatedAt: "2026-08-03T10:00:00.000-03:00",
  },
  {
    id: "aluno-ricardo",
    sindicatoId: sindicato.id,
    nome: "Ricardo Almeida",
    cpf: "123.456.789-12",
    dataNascimento: "1977-02-19",
    telefone: "+5512988880003",
    email: null,
    categoria: "colaborador",
    propriedade: {
      nome: "Haras Primavera",
      municipio: "São José dos Campos",
      car: null,
      itr: "ITR-2026-114",
      atividadePrincipal: "Operação de máquinas",
    },
    comprovanteAtividadeUrl: "/comprovantes/ricardo.pdf",
    associado: false,
    cursosConcluidos: [],
    createdAt: "2026-07-22T08:00:00.000-03:00",
    updatedAt: "2026-08-03T10:00:00.000-03:00",
  },
  {
    id: "aluno-lucas",
    sindicatoId: sindicato.id,
    nome: "Lucas Oliveira",
    cpf: "123.456.789-13",
    dataNascimento: "1994-05-06",
    telefone: "+5512988880004",
    email: "lucas.oliveira@example.com",
    categoria: "publico_geral",
    propriedade: {
      nome: "Nao informado",
      municipio: "Jacarei",
      car: null,
      itr: null,
      atividadePrincipal: "Interesse geral",
    },
    comprovanteAtividadeUrl: null,
    associado: false,
    cursosConcluidos: [],
    createdAt: "2026-08-01T08:00:00.000-03:00",
    updatedAt: "2026-08-03T10:00:00.000-03:00",
  },
];

export const inscricoes: Inscricao[] = [
  {
    id: "inscricao-marina-goiaba",
    sindicatoId: sindicato.id,
    turmaId: "turma-goiaba-agosto",
    cursoId: "curso-goiaba-integrada",
    alunoId: "aluno-marina",
    alunoNome: "Marina Costa",
    cpfSnapshot: "123.456.789-10",
    categoriaSnapshot: "produtor",
    prioridade: 1,
    status: "pendente",
    grupoLiberado: false,
    documentacaoOk: true,
    dataInscricao: "2026-08-03T09:12:00.000-03:00",
    presencas: [],
    percentualFrequencia: 0,
    aprovadoInstrutor: false,
    aptoCertificado: false,
    certificadoEmitido: false,
    certificadoUrl: null,
    certificadoCodigoValidacao: null,
  },
  {
    id: "inscricao-joao-goiaba",
    sindicatoId: sindicato.id,
    turmaId: "turma-goiaba-agosto",
    cursoId: "curso-goiaba-integrada",
    alunoId: "aluno-joao",
    alunoNome: "Joao Marcos Silva",
    cpfSnapshot: "123.456.789-11",
    categoriaSnapshot: "familiar",
    prioridade: 2,
    status: "confirmada",
    grupoLiberado: true,
    documentacaoOk: true,
    dataInscricao: "2026-08-02T16:32:00.000-03:00",
    presencas: [
      { encontroData: "2026-08-18T08:00:00.000-03:00", presente: true },
      { encontroData: "2026-08-19T08:00:00.000-03:00", presente: true },
      { encontroData: "2026-08-20T08:00:00.000-03:00", presente: true },
    ],
    percentualFrequencia: 100,
    aprovadoInstrutor: true,
    aptoCertificado: true,
    certificadoEmitido: false,
    certificadoUrl: null,
    certificadoCodigoValidacao: "SJC-2026-GOI-0001",
  },
  {
    id: "inscricao-ricardo-nr31",
    sindicatoId: sindicato.id,
    turmaId: "turma-nr31-agosto",
    cursoId: "curso-nr-31-maquinas",
    alunoId: "aluno-ricardo",
    alunoNome: "Ricardo Almeida",
    cpfSnapshot: "123.456.789-12",
    categoriaSnapshot: "colaborador",
    prioridade: 3,
    status: "lista_espera",
    grupoLiberado: false,
    documentacaoOk: true,
    dataInscricao: "2026-08-03T10:05:00.000-03:00",
    presencas: [],
    percentualFrequencia: 0,
    aprovadoInstrutor: false,
    aptoCertificado: false,
    certificadoEmitido: false,
    certificadoUrl: null,
    certificadoCodigoValidacao: null,
  },
  {
    id: "inscricao-lucas-bovinos",
    sindicatoId: sindicato.id,
    turmaId: "turma-bovinos-setembro",
    cursoId: "curso-bovinocultura-corte",
    alunoId: "aluno-lucas",
    alunoNome: "Lucas Oliveira",
    cpfSnapshot: "123.456.789-13",
    categoriaSnapshot: "publico_geral",
    prioridade: 4,
    status: "confirmada",
    grupoLiberado: true,
    documentacaoOk: false,
    dataInscricao: "2026-08-01T12:01:00.000-03:00",
    presencas: [
      { encontroData: "2026-09-09T08:00:00.000-03:00", presente: true },
      { encontroData: "2026-09-10T08:00:00.000-03:00", presente: false },
    ],
    percentualFrequencia: 50,
    aprovadoInstrutor: true,
    aptoCertificado: false,
    certificadoEmitido: false,
    certificadoUrl: null,
    certificadoCodigoValidacao: null,
  },
];
